<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Index comparisons</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Results_files/libs/clipboard/clipboard.min.js"></script>
<script src="Results_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Results_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Results_files/libs/quarto-html/popper.min.js"></script>
<script src="Results_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Results_files/libs/quarto-html/anchor.min.js"></script>
<link href="Results_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Results_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Results_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Results_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Results_files/libs/bootstrap/bootstrap-bb462d781dde1847d9e3ccf7736099dd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Index comparisons</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load libraries  </span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyverse' was built under R version 4.5.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.2     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(marginaleffects) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'marginaleffects' was built under R version 4.5.1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gglm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'gglm' was built under R version 4.5.1</code></pre>
</div>
</div>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<section id="climatology-comparison" class="level3">
<h3 class="anchored" data-anchor-id="climatology-comparison">Climatology comparison</h3>
<p>The climatologies of the Index and the Mean Monthly Strength had a significant correlation between them (Pearson correlation = 0.628, p = 0.0286).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/climatology-comparison_full_50.png" class="img-fluid figure-img"></p>
<figcaption>Climatology comparison between EAC CCI and Mean Monthly Strength</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/Scatterplot%2050%20m%20new.png" class="img-fluid figure-img"></p>
<figcaption>Scatterplot of the climatologies</figcaption>
</figure>
</div>
</section>
<section id="relationship-between-index-values-and-mean-monthly-strength" class="level3">
<h3 class="anchored" data-anchor-id="relationship-between-index-values-and-mean-monthly-strength">Relationship between Index values and Mean Monthly Strength</h3>
<p>The raw values of the two were compared, however there was not a strong correlation between the two (Pearson = 0.136, p = 0.31)</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/Scatter%20-%20strength%20v%20index.png" class="img-fluid figure-img"></p>
<figcaption>Scatterplot of Index values against Mean Monthly strength values</figcaption>
</figure>
</div>
<p>To further explore the relationship between the output of the Index and the calculated mean monthly strength values, multiple linear regression models were calculated.</p>
<section id="raw-eac-strength-vs.-copepod-index" class="level4">
<h4 class="anchored" data-anchor-id="raw-eac-strength-vs.-copepod-index">Raw: EAC strength vs.&nbsp;copepod index</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># data wrangling</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract data sources</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>raw_data <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="fu">file.path</span>(<span class="st">"var"</span>, <span class="st">"raw_data_list.rds"</span>))</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>raw_strength_data <span class="ot">&lt;-</span> raw_data<span class="sc">$</span>raw_strength_data</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>raw_index_data <span class="ot">&lt;-</span> raw_data<span class="sc">$</span>raw_index_data</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="co"># combine raw data values</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>comb_raw_data <span class="ot">&lt;-</span> raw_strength_data <span class="sc">%&gt;%</span> </span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">full_join</span>(raw_index_data, <span class="at">by =</span> <span class="st">"date"</span>) <span class="sc">%&gt;%</span>  <span class="co"># inner join to remove NA values</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">month =</span> <span class="fu">month</span>(date) <span class="co"># extract month value</span></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">mean_strength =</span> mean_vel) <span class="sc">%&gt;%</span> </span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(mean_strength) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(eac_cci))</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(comb_raw_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  date                mean_strength eac_cci month
  &lt;dttm&gt;                      &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
1 2011-03-01 00:00:00       0.226   -0.0519     3
2 2011-05-01 00:00:00       0.0925  -0.110      5
3 2011-07-01 00:00:00       0.00652 -0.0420     7
4 2011-12-01 00:00:00       0.186   -0.0323    12
5 2012-04-01 00:00:00       0.0555   0.0490     4
6 2012-09-01 00:00:00       0.140   -0.150      9</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># pivot longer for model</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>comb_raw_data_long <span class="ot">&lt;-</span> comb_raw_data <span class="sc">%&gt;%</span> </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(mean_strength, eac_cci),</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"data_source"</span>,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">"value"</span>) </span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>comb_raw_data_long<span class="sc">$</span>month <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(comb_raw_data_long<span class="sc">$</span>month)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(comb_raw_data_long)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  date                month data_source      value
  &lt;dttm&gt;              &lt;fct&gt; &lt;chr&gt;            &lt;dbl&gt;
1 2011-03-01 00:00:00 3     mean_strength  0.226  
2 2011-03-01 00:00:00 3     eac_cci       -0.0519 
3 2011-05-01 00:00:00 5     mean_strength  0.0925 
4 2011-05-01 00:00:00 5     eac_cci       -0.110  
5 2011-07-01 00:00:00 7     mean_strength  0.00652
6 2011-07-01 00:00:00 7     eac_cci       -0.0420 </code></pre>
</div>
</div>
<p>data_source is whether the values come from the output of the EAC CCI Index calculation or are the Mean monthly strength values from the Copernicus Global Ocean Physics Reanalysis <a href="https://data.marine.copernicus.eu/product/GLOBAL_MULTIYEAR_PHY_001_030/description" class="uri">https://data.marine.copernicus.eu/product/GLOBAL_MULTIYEAR_PHY_001_030/description</a>.</p>
<p>There are no samples taken in January, so the data only covers the period from February to December.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> comb_raw_data_long, <span class="fu">aes</span>(<span class="at">x =</span> data_source, <span class="at">y =</span> value)) <span class="sc">+</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">data =</span> comb_raw_data_long,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>             <span class="fu">aes</span>(<span class="at">x =</span> data_source, <span class="at">y =</span> value), <span class="at">width =</span> <span class="fl">0.2</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Results_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A multiple linear regression was conducted to examine the effects of the data source, month, and their interaction on the resulting values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create the model</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>raw_data_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(value <span class="sc">~</span> data_source <span class="sc">*</span> month, <span class="at">data =</span> comb_raw_data_long)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(raw_data_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = value ~ data_source * month, data = comb_raw_data_long)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.22308 -0.05354  0.00000  0.03956  0.21407 

Coefficients:
                                 Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)                       0.10564    0.08567   1.233   0.2206  
data_sourcemean_strength          0.06037    0.12115   0.498   0.6195  
month3                            0.06551    0.09253   0.708   0.4807  
month4                           -0.00716    0.09086  -0.079   0.9374  
month5                           -0.19189    0.09578  -2.004   0.0480 *
month6                           -0.08922    0.09384  -0.951   0.3442  
month7                           -0.15957    0.09086  -1.756   0.0823 .
month8                           -0.14802    0.09253  -1.600   0.1130  
month9                           -0.18860    0.09578  -1.969   0.0519 .
month10                          -0.13403    0.09578  -1.399   0.1650  
month11                          -0.15661    0.09384  -1.669   0.0985 .
month12                          -0.08105    0.09158  -0.885   0.3784  
data_sourcemean_strength:month3  -0.04611    0.13086  -0.352   0.7254  
data_sourcemean_strength:month4  -0.06550    0.12850  -0.510   0.6115  
data_sourcemean_strength:month5   0.09980    0.13545   0.737   0.4631  
data_sourcemean_strength:month6   0.01562    0.13271   0.118   0.9066  
data_sourcemean_strength:month7   0.09677    0.12850   0.753   0.4533  
data_sourcemean_strength:month8   0.06103    0.13086   0.466   0.6420  
data_sourcemean_strength:month9   0.15367    0.13545   1.135   0.2595  
data_sourcemean_strength:month10  0.04757    0.13545   0.351   0.7262  
data_sourcemean_strength:month11  0.21228    0.13271   1.600   0.1131  
data_sourcemean_strength:month12  0.11019    0.12952   0.851   0.3970  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.08567 on 94 degrees of freedom
Multiple R-squared:  0.5779,    Adjusted R-squared:  0.4836 
F-statistic: 6.128 on 21 and 94 DF,  p-value: 2.892e-10</code></pre>
</div>
</div>
<p>The overall model was statistically significant, <em>F</em>(21, 94) = 6.128, <em>p</em> &lt; 0.001, explaining approximately 48.4% of the variance in the dependent variable (<em>R²</em> = 0.5779, adjusted <em>R²</em> = 0.486).</p>
<p>Residuals were symmetrically distributed with a standard error of 0.08567 (df = 94), ranging from -0.223 to 0.214, suggesting that the model does not under or overfit.</p>
<p>A second regression was conducted to remove the effect of the interaction between data source and month.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># drop the interaction term</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>raw_data_model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(value <span class="sc">~</span> data_source <span class="sc">+</span> month, <span class="at">data =</span> comb_raw_data_long)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(raw_data_model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = value ~ data_source + month, data = comb_raw_data_long)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.181325 -0.066135 -0.004903  0.064038  0.188757 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)               0.07586    0.06585   1.152   0.2520    
data_sourcemean_strength  0.11993    0.01715   6.995 2.65e-10 ***
month3                    0.04246    0.07052   0.602   0.5484    
month4                   -0.03991    0.06925  -0.576   0.5656    
month5                   -0.14199    0.07299  -1.945   0.0544 .  
month6                   -0.08141    0.07152  -1.138   0.2576    
month7                   -0.11119    0.06925  -1.606   0.1114    
month8                   -0.11751    0.07052  -1.666   0.0987 .  
month9                   -0.11176    0.07299  -1.531   0.1288    
month10                  -0.11024    0.07299  -1.510   0.1340    
month11                  -0.05047    0.07152  -0.706   0.4819    
month12                  -0.02595    0.06979  -0.372   0.7108    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.09233 on 104 degrees of freedom
Multiple R-squared:  0.4575,    Adjusted R-squared:  0.4001 
F-statistic: 7.973 on 11 and 104 DF,  p-value: 6.437e-10</code></pre>
</div>
</div>
<p>This model was also statistically significant, F(11, 104) = 7.973, p &lt; 0.001, explaining approximately 40% variance in the dependent variable (<em>R²</em> = 0.458, adjusted <em>R²</em> = 0.4).</p>
<ul>
<li>The main effect of data source was statistically significant (<em>β</em> = 0.1199, <em>t</em> = 6.995, <em>p</em> &lt; 0.001).</li>
</ul>
<p>Residuals were symmetrically distributed with a standard error of 0.09233, ranging from -0.181 to 0.188.</p>
<p>To assess whether the interaction between month and the source of data significantly improves the model fit, an analysis of variance (ANOVA) was conducted comparing two nested models:</p>
<ul>
<li><p><strong>Model 1</strong>: included main effects of <code>data_source</code> and <code>month</code>, as well as their interaction (<code>month:data_source</code>).</p></li>
<li><p><strong>Model 2</strong>: included only the main effects of <code>data_source</code> and <code>month</code>.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compare the two models </span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(raw_data_model, raw_data_model2, <span class="at">test =</span> <span class="st">"F"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: value ~ data_source * month
Model 2: value ~ data_source + month
  Res.Df     RSS  Df Sum of Sq      F   Pr(&gt;F)   
1     94 0.68984                                 
2    104 0.88656 -10  -0.19672 2.6806 0.006254 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The comparison revealed that Model 1 provided a significantly better fit to the data than Model 2, <em>F</em>(10, 94) = 2.68, <em>p</em> = 0.006.</p>
<p>This suggests that the seasonal trends differs between the index and the strength values.</p>
<p>Diagnostics of Model 1 show that the values have a fairly normal distribution. There is however, an unusual point in the leverage plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># look at model 1</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">gglm</span>(raw_data_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Results_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A plot showing the model’s predicted values for different months and data sources, overlaid with actual raw data points using jitter to visualize the model’s fit to the observed data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_predictions</span>(raw_data_model, <span class="at">condition =</span> <span class="fu">c</span>(<span class="st">'month'</span>, <span class="st">'data_source'</span>)) <span class="sc">+</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">data =</span> comb_raw_data_long,</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>             <span class="fu">aes</span>(<span class="at">x =</span> month, <span class="at">y =</span> value), <span class="at">width =</span> <span class="fl">0.2</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Results_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="data-transformation" class="level4">
<h4 class="anchored" data-anchor-id="data-transformation">Data transformation</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># log transform the data</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>comb_raw_data_long <span class="ot">&lt;-</span> comb_raw_data_long <span class="sc">%&gt;%</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">log1pvalue =</span> <span class="fu">ifelse</span>(value <span class="sc">&gt;=</span> <span class="sc">-</span><span class="dv">1</span>, <span class="fu">log1p</span>(value), <span class="cn">NA</span>))</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(comb_raw_data_long)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  date                month data_source      value log1pvalue
  &lt;dttm&gt;              &lt;fct&gt; &lt;chr&gt;            &lt;dbl&gt;      &lt;dbl&gt;
1 2011-03-01 00:00:00 3     mean_strength  0.226      0.204  
2 2011-03-01 00:00:00 3     eac_cci       -0.0519    -0.0533 
3 2011-05-01 00:00:00 5     mean_strength  0.0925     0.0885 
4 2011-05-01 00:00:00 5     eac_cci       -0.110     -0.117  
5 2011-07-01 00:00:00 7     mean_strength  0.00652    0.00650
6 2011-07-01 00:00:00 7     eac_cci       -0.0420    -0.0429 </code></pre>
</div>
</div>
<p>Redo the linear regression with the log transformed values</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create the model</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>raw_data_model_log <span class="ot">&lt;-</span> <span class="fu">lm</span>(log1pvalue <span class="sc">~</span> data_source <span class="sc">*</span> month, <span class="at">data =</span> comb_raw_data_long)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(raw_data_model_log)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log1pvalue ~ data_source * month, data = comb_raw_data_long)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.20593 -0.05183  0.00000  0.04052  0.19495 

Coefficients:
                                  Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)                       0.100424   0.082047   1.224   0.2240  
data_sourcemean_strength          0.053159   0.116032   0.458   0.6479  
month3                            0.052183   0.088621   0.589   0.5574  
month4                           -0.008317   0.087024  -0.096   0.9241  
month5                           -0.196476   0.091732  -2.142   0.0348 *
month6                           -0.089714   0.089878  -0.998   0.3208  
month7                           -0.157144   0.087024  -1.806   0.0742 .
month8                           -0.148833   0.088621  -1.679   0.0964 .
month9                           -0.188472   0.091732  -2.055   0.0427 *
month10                          -0.139044   0.091732  -1.516   0.1329  
month11                          -0.155375   0.089878  -1.729   0.0871 .
month12                          -0.081344   0.087712  -0.927   0.3561  
data_sourcemean_strength:month3  -0.037307   0.125329  -0.298   0.7666  
data_sourcemean_strength:month4  -0.057600   0.123071  -0.468   0.6409  
data_sourcemean_strength:month5   0.114091   0.129728   0.879   0.3814  
data_sourcemean_strength:month6   0.023128   0.127107   0.182   0.8560  
data_sourcemean_strength:month7   0.099245   0.123071   0.806   0.4220  
data_sourcemean_strength:month8   0.069795   0.125329   0.557   0.5789  
data_sourcemean_strength:month9   0.156087   0.129728   1.203   0.2319  
data_sourcemean_strength:month10  0.060235   0.129728   0.464   0.6435  
data_sourcemean_strength:month11  0.201396   0.127107   1.584   0.1164  
data_sourcemean_strength:month12  0.105161   0.124044   0.848   0.3987  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.08205 on 94 degrees of freedom
Multiple R-squared:  0.5777,    Adjusted R-squared:  0.4833 
F-statistic: 6.122 on 21 and 94 DF,  p-value: 2.953e-10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gglm</span>(raw_data_model_log)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Results_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create the model</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>raw_data_model_log2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log1pvalue <span class="sc">~</span> data_source <span class="sc">+</span> month, <span class="at">data =</span> comb_raw_data_long)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(raw_data_model_log2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log1pvalue ~ data_source + month, data = comb_raw_data_long)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.202503 -0.061334 -0.001394  0.057876  0.174343 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)               0.06845    0.06291   1.088   0.2790    
data_sourcemean_strength  0.11710    0.01638   7.149 1.25e-10 ***
month3                    0.03353    0.06737   0.498   0.6197    
month4                   -0.03712    0.06615  -0.561   0.5760    
month5                   -0.13943    0.06973  -1.999   0.0482 *  
month6                   -0.07815    0.06832  -1.144   0.2553    
month7                   -0.10752    0.06615  -1.625   0.1071    
month8                   -0.11394    0.06737  -1.691   0.0938 .  
month9                   -0.11043    0.06973  -1.584   0.1163    
month10                  -0.10893    0.06973  -1.562   0.1213    
month11                  -0.05468    0.06832  -0.800   0.4254    
month12                  -0.02876    0.06668  -0.431   0.6671    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.08821 on 104 degrees of freedom
Multiple R-squared:   0.46, Adjusted R-squared:  0.4028 
F-statistic: 8.052 on 11 and 104 DF,  p-value: 5.204e-10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compare the two models </span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(raw_data_model_log, raw_data_model_log2, <span class="at">test =</span> <span class="st">"F"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: log1pvalue ~ data_source * month
Model 2: log1pvalue ~ data_source + month
  Res.Df     RSS  Df Sum of Sq      F   Pr(&gt;F)   
1     94 0.63279                                 
2    104 0.80914 -10  -0.17636 2.6198 0.007436 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The model with the interaction included explains significantly more of the variation in the data.</p>
<p>Using the AIC, the two best models of the log-transformed data and the non-log-transformed data were compared to determine whether the log-transformed data provides a better explanation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(raw_data_model, raw_data_model_log)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   df       AIC
raw_data_model     23 -219.2923
raw_data_model_log 23 -229.3071</code></pre>
</div>
</div>
<p>The model without the log transformations has a lower AIC value, suggesting that it is a better fit.</p>
</section>
</section>
</section>
<section id="comparing-the-anomalies" class="level2">
<h2 class="anchored" data-anchor-id="comparing-the-anomalies">Comparing the anomalies</h2>
<p>Anomalies were calculated by subtracting the climatology value from the strength/index value, for example, <code>strength_anom = mean_str - str_clim</code>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/eac_cci_str_combined.png" class="img-fluid figure-img"></p>
<figcaption>Anomalies of Index and mean monthly strength against climatologies, plotted over time</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/Sactterplot%20of%20anomalies.png" class="img-fluid figure-img"></p>
<figcaption>Scatterplot of Index and Mean Monthly Strength anomalies</figcaption>
</figure>
</div>
<p>There was no correlation between the two (Pearson correlation = -0.043, p = 0.749).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract data sources</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>combined_anomaly_data <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="fu">file.path</span>(<span class="st">"var"</span>, <span class="st">"combined_anomalies.rds"</span>))</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(combined_anomaly_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  trip_month          index_anom strength_anom
  &lt;dttm&gt;                   &lt;dbl&gt;         &lt;dbl&gt;
1 2011-03-01 00:00:00    -0.148         0.0710
2 2011-05-01 00:00:00    -0.131        -0.0216
3 2011-07-01 00:00:00     0.0376       -0.0989
4 2011-12-01 00:00:00    -0.0768        0.0191
5 2012-04-01 00:00:00    -0.0185       -0.107 
6 2012-09-01 00:00:00    -0.0651        0.0334</code></pre>
</div>
</div>
<p>The combined_anomalies2 tibble has 2 key variables:</p>
<ol type="1">
<li><p>index_anom : The Index anomalies</p></li>
<li><p>strength_anom : The strength anomalies calculated from the Copernicus data</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># prepare data for analysis</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>combined_anomaly_data <span class="ot">&lt;-</span> combined_anomaly_data <span class="sc">%&gt;%</span> </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">month =</span> <span class="fu">month</span>(trip_month)) </span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(combined_anomaly_data)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  trip_month          index_anom strength_anom month
  &lt;dttm&gt;                   &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;
1 2011-03-01 00:00:00    -0.148         0.0710     3
2 2011-05-01 00:00:00    -0.131        -0.0216     5
3 2011-07-01 00:00:00     0.0376       -0.0989     7
4 2011-12-01 00:00:00    -0.0768        0.0191    12
5 2012-04-01 00:00:00    -0.0185       -0.107      4
6 2012-09-01 00:00:00    -0.0651        0.0334     9</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>combined_anomaly_data_long <span class="ot">&lt;-</span> combined_anomaly_data <span class="sc">%&gt;%</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(index_anom, strength_anom),</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"anomaly_type"</span>,</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">"value"</span>) </span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>combined_anomaly_data_long<span class="sc">$</span>month <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(combined_anomaly_data_long<span class="sc">$</span>month)</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(combined_anomaly_data_long)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  trip_month          month anomaly_type    value
  &lt;dttm&gt;              &lt;fct&gt; &lt;chr&gt;           &lt;dbl&gt;
1 2011-03-01 00:00:00 3     index_anom    -0.148 
2 2011-03-01 00:00:00 3     strength_anom  0.0710
3 2011-05-01 00:00:00 5     index_anom    -0.131 
4 2011-05-01 00:00:00 5     strength_anom -0.0216
5 2011-07-01 00:00:00 7     index_anom     0.0376
6 2011-07-01 00:00:00 7     strength_anom -0.0989</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># model to compare the anomalies of the Index and the Strength values</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>anomaly_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(value <span class="sc">~</span> anomaly_type <span class="sc">*</span> month, <span class="at">data =</span> combined_anomaly_data_long)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anomaly_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = value ~ anomaly_type * month, data = combined_anomaly_data_long)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.223163 -0.052084  0.000463  0.039115  0.214287 

Coefficients:
                                   Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)                        0.005998   0.085094   0.070    0.944
anomaly_typestrength_anom         -0.001885   0.120341  -0.016    0.988
month3                             0.069376   0.091912   0.755    0.452
month4                             0.024073   0.090256   0.267    0.790
month5                            -0.113273   0.095138  -1.191    0.237
month6                             0.046492   0.093216   0.499    0.619
month7                             0.019880   0.090256   0.220    0.826
month8                             0.048566   0.091912   0.528    0.598
month9                            -0.003360   0.095138  -0.035    0.972
month10                            0.018474   0.095138   0.194    0.846
month11                           -0.052379   0.093216  -0.562    0.576
month12                           -0.026045   0.090969  -0.286    0.775
anomaly_typestrength_anom:month3  -0.040368   0.129983  -0.311    0.757
anomaly_typestrength_anom:month4  -0.063928   0.127641  -0.501    0.618
anomaly_typestrength_anom:month5   0.055350   0.134545   0.411    0.682
anomaly_typestrength_anom:month6  -0.061036   0.131827  -0.463    0.644
anomaly_typestrength_anom:month7  -0.017470   0.127641  -0.137    0.891
anomaly_typestrength_anom:month8  -0.083191   0.129983  -0.640    0.524
anomaly_typestrength_anom:month9   0.008262   0.134545   0.061    0.951
anomaly_typestrength_anom:month10 -0.082595   0.134545  -0.614    0.541
anomaly_typestrength_anom:month11  0.124864   0.131827   0.947    0.346
anomaly_typestrength_anom:month12  0.057393   0.128650   0.446    0.657

Residual standard error: 0.08509 on 94 degrees of freedom
Multiple R-squared:  0.247, Adjusted R-squared:  0.0788 
F-statistic: 1.468 on 21 and 94 DF,  p-value: 0.1081</code></pre>
</div>
</div>
<p>The model was not statistically significant, <em>F</em>(21, 94) = 1.47, <em>p</em> = 0.1081, and explained only a 7.9 %of the variance in the Index anomalies (<em>R²</em> = 0.247, adjusted <em>R²</em> = 0.079).</p>
<p>The residuals were approximately symmetrically distributed, with a standard error of 0.0851, and ranged from -0.223 to 0.214.</p>
<p>Neither anomaly type, month, nor their interaction had a significant effect on value<strong>.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># model to compare the anomalies of the Index and the Strength values</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>anomaly_model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(value <span class="sc">~</span> anomaly_type <span class="sc">+</span> month, <span class="at">data =</span> combined_anomaly_data_long)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anomaly_model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = value ~ anomaly_type + month, data = combined_anomaly_data_long)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.209424 -0.060854 -0.005372  0.053024  0.205331 

Coefficients:
                            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)                0.0124426  0.0625019   0.199    0.843
anomaly_typestrength_anom -0.0147743  0.0162741  -0.908    0.366
month3                     0.0491919  0.0669352   0.735    0.464
month4                    -0.0078910  0.0657291  -0.120    0.905
month5                    -0.0855983  0.0692846  -1.235    0.219
month6                     0.0159744  0.0678847   0.235    0.814
month7                     0.0111450  0.0657291   0.170    0.866
month8                     0.0069701  0.0669352   0.104    0.917
month9                     0.0007711  0.0692846   0.011    0.991
month10                   -0.0228236  0.0692846  -0.329    0.743
month11                    0.0100528  0.0678847   0.148    0.883
month12                    0.0026514  0.0662487   0.040    0.968

Residual standard error: 0.08764 on 104 degrees of freedom
Multiple R-squared:  0.1163,    Adjusted R-squared:  0.02287 
F-statistic: 1.245 on 11 and 104 DF,  p-value: 0.2675</code></pre>
</div>
</div>
<p>The model was not statistically significant, <em>F</em>(11, 104) = 1.245, <em>p</em> = 0.2675, and explained only 2.3 % of the variance in the Index anomalies (<em>R²</em> = 0.116, adjusted <em>R²</em> = 0.023).</p>
<p>The residuals were approximately symmetrically distributed, with a standard error of 0.0851, and ranged from -0.209 to 0.205.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gglm</span>(anomaly_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Results_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gglm</span>(anomaly_model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Results_files/figure-html/unnamed-chunk-17-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="north-vs-south" class="level2">
<h2 class="anchored" data-anchor-id="north-vs-south">North vs South</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load north and south data</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>cci_data_n <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="fu">file.path</span>(<span class="st">"var"</span>, <span class="st">"eac_cci_north.rds"</span>))</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>samples_n <span class="ot">&lt;-</span> cci_data_n<span class="sc">$</span>samples</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>rda_fit_n <span class="ot">&lt;-</span> cci_data_n<span class="sc">$</span>rda_fit</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>lm_fit_n <span class="ot">&lt;-</span> cci_data_n<span class="sc">$</span>lm_fit</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>climatology_n <span class="ot">&lt;-</span> cci_data_n<span class="sc">$</span>climatology</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>month_data_n <span class="ot">&lt;-</span> cci_data_n<span class="sc">$</span>month_data <span class="co"># monthly average Index value</span></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>cci_data_s <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="fu">file.path</span>(<span class="st">"var"</span>, <span class="st">"eac_cci_south.rds"</span>))</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>samples_s <span class="ot">&lt;-</span> cci_data_s<span class="sc">$</span>samples</span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>rda_fit_s <span class="ot">&lt;-</span> cci_data_s<span class="sc">$</span>rda_fit</span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a>lm_fit_s <span class="ot">&lt;-</span> cci_data_s<span class="sc">$</span>lm_fit</span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a>climatology_s <span class="ot">&lt;-</span> cci_data_s<span class="sc">$</span>climatology</span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a>month_data_s <span class="ot">&lt;-</span> cci_data_s<span class="sc">$</span>month_data <span class="co"># monthly average Index value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>